version: '3.1'

# Build the docker image locally and publish it to your local Docker registry (see scripts/)
services:
  # Seed nodes starts up and join itself and other seed nodes
  # This must always have a replication of 1 and no more otherwise you will cause a split-brain scenario
  application-seed-1:
    image:  rubixcubin/akka-cluster-sample:1.5
    environment:
      PUBLISH_HOST: application-seed-1
      PUBLISH_PORT: 2551
      SEED_NODE_1: akka.tcp://akka-cluster-sample@application-seed-1:2551
      SEED_NODE_2: akka.tcp://akka-cluster-sample@application-seed-2:2551
    networks:
      - akka-cluster
    deploy:
      replicas: 1
      restart_policy:
        condition: any
        delay: 10s
  application-seed-2:
    image:  rubixcubin/akka-cluster-sample:1.5
    environment:
      PUBLISH_HOST: application-seed-2
      PUBLISH_PORT: 2551
      SEED_NODE_1: akka.tcp://akka-cluster-sample@application-seed-1:2551
      SEED_NODE_2: akka.tcp://akka-cluster-sample@application-seed-2:2551
    networks:
      - akka-cluster
    deploy:
      replicas: 1
      restart_policy:
        condition: any
        delay: 10s

  # Other nodes always join the seed node on startup
  application:
    image: rubixcubin/akka-cluster-sample:1.5
    environment:
      SEED_NODE_1: akka.tcp://akka-cluster-sample@application-seed-1:2551
      SEED_NODE_2: akka.tcp://akka-cluster-sample@application-seed-2:2551
    networks:
      - akka-cluster
    depends_on:
      - application-seed-1
      - application-seed-2
    deploy:
      replicas: 3
      restart_policy:
        condition: any
        delay: 20s
      update_config:
        parallelism: 1
        delay: 10s

networks:
  akka-cluster:
